feat - Make project with Hello World by Marlon
MarlonPrado/LifeList-App pull request #1
Opened 2024-03-18 05:54 UTC by MarlonPrado

Hello, this is my first pull request after quite some time. I created the project with the classic "Hello World" from me in Kotlin. I also added the respective readme.md document at the beginning and a .gitignore file to ignore those cache files generated during the compilation process😎✔

2024-04-01 13:38 UTC, jorlugaqui requested changes
Please fix the gitignore file and location.

Final score: 4.0

2024-04-01 13:38 UTC, jorlugaqui commented on .gitignore.txt
> +# Built application files
We don't need this file. Please remove it.

2024-04-01 13:38 UTC, jorlugaqui commented on app/.gitignore
> +/build
This file should be located at the root folder.

2024-04-07 20:47 UTC, MarlonPrado reviewed
changues are applied

2024-04-21 15:33 UTC, jorlugaqui approved these changes
Chicos, apruebo el PR. Pero por favor, agreguen el .gitignore en la raíz del proyecto (no vi ninguno).

2024-04-21 20:15 UTC, merged